FROM openjdk:21
LABEL authors="juspin"

COPY ./transaction-management-system-1.0.1-SNAPSHOT.jar /transaction-management-system-1.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "transaction-management-system-1.0.1-SNAPSHOT.jar"]